### ISSUE TITLE
Errors with some repositories (Datadog, Grafana)

### ISSUE THREAD

**Issue by mNantern** [dvershinin/lastversion#2]
Thank you for this useful project, it works very well !

Except for 2 repositories: 
- [Grafana](https://github.com/grafana/grafana/releases) : the latest version is `6.2.2` and lastversion outputs `5.4.4`
- [Datadog-agent](https://github.com/DataDog/datadog-agent/releases) : lastversion fails with an error:

```
Traceback (most recent call last):
  File "/usr/local/bin/lastversion", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/lastversion/lastversion.py", line 95, in main
    version = latest(args.repo, args.sniff, args.validate)
  File "/usr/local/lib/python2.7/site-packages/lastversion/lastversion.py", line 41, in latest
    the_version = release.find("a").text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by dvershinin** [comment]
Thanks for the bug report. Fixed and released 0.0.9 with tests and fixes.

**Comment by mNantern** [comment]
That's great, thank you ! But in the process it looks like you broke something.

For example now the repository [roer](https://github.com/spinnaker/roer/releases) is failing :

```
Traceback (most recent call last):
  File "/usr/local/bin/lastversion", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/lastversion/lastversion.py", line 153, in main
    version = latest(args.repo, args.sniff, args.validate, args.format)
  File "/usr/local/lib/python3.7/site-packages/lastversion/lastversion.py", line 100, in latest
    description = r.find(class_='markdown-body').text
AttributeError: 'NoneType' object has no attribute 'text'
```

It was working in version 0.0.8.

**Comment by dvershinin** [comment]
Some update with new options (`--format json`) caused it. The 0.0.10 (just released) should fix that. 
Added test for that repo as well.

Thanks.

**Comment by mNantern** [comment]
Unfortunately I think something went wrong with the release. I now always have the following error with v0.0.10:

```
Traceback (most recent call last):
  File "/usr/local/bin/lastversion", line 6, in <module>
    from lastversion import main
  File "/usr/local/lib/python3.7/site-packages/lastversion/__init__.py", line 9, in <module>
    from .lastversion import main
  File "/usr/local/lib/python3.7/site-packages/lastversion/lastversion.py", line 16, in <module>
    from __about__ import __version__
ModuleNotFoundError: No module named '__about__'
```

**Comment by dvershinin** [comment]
I've been testing with Python 2.7 mainly. Now with 3.6 confirmed the issue and the fix was very simple.
Released 0.0.11 and now testing Python 3.7 as well.

**Comment by mNantern** [comment]
Everything is working great now, thank you 👍
